# Generated by Django 4.2.5 on 2023-09-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='born',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Страна рождения'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='fname',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='lname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='agerate',
            name='rate',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')], max_length=20, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='director',
            name='fname',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='director',
            name='lname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='actor',
            field=models.ManyToManyField(to='catalog.actor', verbose_name='Актёр'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='ager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.agerate', verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.director', verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='rating',
            field=models.FloatField(verbose_name='Реётинг'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.status', verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='summary',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('бесплатно', 'бесплатно'), ('базовая', 'базовая'), ('супер', 'супер')], max_length=20, verbose_name='Подписка'),
        ),
    ]
